### ISSUE TITLE
VDOM Support not working

### ISSUE THREAD

**Issue by hhansen06** [benclerc/Fortinet-FortiOSAPI#1]
Hey, first of: thanks for the project. helped a lot.

when using the vdom parameter in one of the get functions, the urlencode method breaks.

`  urlencode(): Argument #1 ($string) must be of type string, array given

  at vendor\benclerc\fortinet-fortiosapi\src\Fortinet\FortiOSAPI\FortiOSAPI.php:185
    181▕ 
    182▕                                // Else with classicly insert values in query
    183▕                                default:
    184▕                                        if ($first) { $first = FALSE; }
    185▕                                        $query .= urlencode($key).'='.urlencode($value);
    186▕                                        break;
    187▕                        }
    188▕                }
    189▕`

changing the vdom parameter in e.g. getAllFirewallAddress to type string worked for me.

**Comment by sin0light** [comment]
Hi @hhansen06,

Thanks for your message. Do you think that imploding the array into the comma separated string would solve the issue ?
I have not been working with this library for a while now ...

Ben

**Comment by benclerc** [comment]
Hi @hhansen06,

Thanks for your message. Do you think that imploding the array into the comma separated string would solve the issue ?
I have not been working with this library for a while now ...

Ben

**Comment by hhansen06** [comment]
hey ben, absolutely. i just tried, imploding the array to , seperated string, would work.
thanks for your work!

**Comment by benclerc** [comment]
I fixed it as discussed !
